all:
  children:
    devops:
      hosts:
        sonarqube:
          ansible_host: "{{ hostvars['localhost']['sonarqube_ip'] }}"
        monitoring:
          ansible_host: "{{ hostvars['localhost']['monitoring_ip'] }}"
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
    runners:
      hosts:
        github-runner:
          ansible_host: "{{ hostvars['localhost']['github_runner_ip'] }}"
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa