all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/projet-c.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    cicd:
      children:
        jenkins:
          hosts:
            jenkins-server:
              ansible_host: "{{ jenkins_ip }}"
        
        jenkins_agents:
          hosts:
            jenkins-agent:
              ansible_host: "{{ jenkins_agent_ip }}"
        
        gitlab:
          hosts:
            gitlab-server:
              ansible_host: "{{ gitlab_ip }}"
        
        gitlab_runners:
          hosts:
            gitlab-runner:
              ansible_host: "{{ gitlab_runner_ip }}"
        
        github_runners:
          hosts:
            github-runner:
              ansible_host: "{{ github_runner_ip }}"
        
        sonarqube:
          hosts:
            sonarqube-server:
              ansible_host: "{{ sonarqube_ip }}"