---
- name: Configuration de Jenkins
  hosts: jenkins
  become: true
  vars:
    java_packages:
      - openjdk-21-jdk
    jenkins_admin_username: admin
    jenkins_admin_password: "{{ lookup('env', 'JENKINS_ADMIN_PASSWORD') }}"
    jenkins_plugins:
      - git
      - workflow-aggregator
      - pipeline-stage-view
      - docker-workflow
      - kubernetes
      - blueocean
      - github
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    jenkins_http_port: 8080
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

- name: Générer un token API Jenkins pour l'utilisateur admin
  uri:
    url: "http://localhost:8080/user/admin/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken"
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "newTokenName=ansible-token"
    body_format: form-urlencoded
  register: jenkins_token_response

- name: Extraire le token Jenkins
  set_fact:
    jenkins_api_token: "{{ jenkins_token_response.json.data.tokenValue }}"

- name: Create a Jenkins node using token authentication
  community.general.jenkins_node:
    url: "{{ lookup('env', 'JENKINS_MASTER_URL') }}"
    user: jenkins
    token: "{{ jenkins_api_token }}"
    name: my-node
    state: present
