---
- name: Configuration de Jenkins
  hosts: jenkins
  become: true
  vars:
    java_packages:
      - openjdk-17-jdk
    jenkins_admin_username: "{{ lookup('env', 'JENKINS_ADMIN_USERNAME') }}"
    jenkins_admin_password: "{{ lookup('env', 'JENKINS_ADMIN_PASSWORD') }}"
    git_repo_url: "{{ lookup('env', 'GIT_REPO_URL') | default('https://github.com/votre-utilisateur/projet-c-app.git') }}"
    git_credentials_id: "{{ lookup('env', 'GIT_CREDENTIALS_ID') | default('') }}"
    aws_credentials_base64: "{{ lookup('env', 'AWS_CREDENTIALS_BASE64') | default('') }}"
    jenkins_plugins:
      - git
      - workflow-aggregator
      - pipeline-stage-view
      - docker-workflow
      - kubernetes
      - blueocean
      - github
      - credentials-binding
      - ws-cleanup
      - ansicolor
      - terraform
      - aws-credentials
      - plain-credentials
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    jenkins_http_port: 8080
  pre_tasks:
    - name: Enable 'universe' repository on Ubuntu
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
      when: ansible_distribution == 'Ubuntu'
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installation des outils nécessaires pour Terraform et AWS
      apt:
        name:
          - jq
          - unzip
          - python3-pip
          - curl
        state: present
        
    - name: Téléchargement d'AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'
        
    - name: Extraction d'AWS CLI v2
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes
        creates: /tmp/aws
        
    - name: Installation d'AWS CLI v2
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws
        
    - name: Téléchargement de Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /tmp/terraform.zip
        mode: '0644'
      
    - name: Installation de Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        creates: /usr/local/bin/terraform

    - name: Activer NTP avec timedatectl
      become: yes
      ansible.builtin.command: timedatectl set-ntp true
      changed_when: false

    - name: Configurer la timezone sur Europe/Paris
      timezone:
        name: Europe/Paris

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      jenkins_plugins: "{{ jenkins_plugins }}"
