---
- name: Configuration du runner GitHub
  hosts: github-runner
  become: true
  gather_facts: false
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/projet-c.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - git
          - docker.io
        state: present
        update_cache: yes
      ignore_errors: true
      
    - name: Démarrer et activer Docker
      systemd:
        name: docker
        state: started
        enabled: true
      ignore_errors: true
      
    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: true
      ignore_errors: true
      
    - name: Créer le répertoire pour le runner
      file:
        path: /home/ubuntu/actions-runner
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      ignore_errors: true
      
    - name: Télécharger le runner GitHub
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
        dest: /home/ubuntu/actions-runner/actions-runner.tar.gz
        mode: '0644'
      ignore_errors: true
      
    - name: Extraire l'archive du runner
      unarchive:
        src: /home/ubuntu/actions-runner/actions-runner.tar.gz
        dest: /home/ubuntu/actions-runner
        remote_src: true
        owner: ubuntu
        group: ubuntu
      ignore_errors: true
      
    - name: Configurer le runner
      shell: |
        cd /home/ubuntu/actions-runner
        ./config.sh --url https://github.com/{{ github_repo }} --token {{ runner_token }} --name "EC2-Runner" --unattended
      become_user: ubuntu
      ignore_errors: true
      
    - name: Installer le service du runner
      shell: |
        cd /home/ubuntu/actions-runner
        ./svc.sh install
      ignore_errors: true
      
    - name: Démarrer le service du runner
      shell: |
        cd /home/ubuntu/actions-runner
        ./svc.sh start
      ignore_errors: true

- name: Configuration de SonarQube
  hosts: sonarqube
  become: true
  gather_facts: false
  tasks:
    - name: Attendre que SSH soit disponible
      wait_for_connection:
        delay: 10
        timeout: 300
      
    - name: Installer les dépendances
      apt:
        name:
          - openjdk-17-jdk
          - unzip
          - wget
        state: present
        update_cache: yes
      ignore_errors: true
      
    - name: Créer l'utilisateur sonarqube
      user:
        name: sonarqube
        shell: /bin/bash
        home: /opt/sonarqube
        create_home: true
      ignore_errors: true
      
    - name: Télécharger SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.1.69595.zip
        dest: /tmp/sonarqube.zip
        mode: '0644'
      ignore_errors: true
      
    - name: Extraire SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt
        remote_src: true
        owner: sonarqube
        group: sonarqube
      ignore_errors: true
      
    - name: Créer un lien symbolique
      file:
        src: /opt/sonarqube-9.9.1.69595
        dest: /opt/sonarqube
        state: link
        owner: sonarqube
        group: sonarqube
      ignore_errors: true
      
    - name: Créer le service SonarQube
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=network.target
          
          [Service]
          Type=simple
          User=sonarqube
          Group=sonarqube
          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
      ignore_errors: true
      
    - name: Recharger systemd
      systemd:
        daemon_reload: true
      ignore_errors: true
      
    - name: Démarrer et activer SonarQube
      systemd:
        name: sonarqube
        state: started
        enabled: true
      ignore_errors: true

- name: Configuration du monitoring
  hosts: monitoring
  become: true
  gather_facts: false
  tasks:
    - name: Attendre que SSH soit disponible
      wait_for_connection:
        delay: 10
        timeout: 300
      
    - name: Installer les dépendances
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes
      ignore_errors: true
      
    - name: Démarrer et activer Docker
      systemd:
        name: docker
        state: started
        enabled: true
      ignore_errors: true
      
    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: true
      ignore_errors: true
      
    - name: Créer le répertoire pour Prometheus et Grafana
      file:
        path: /home/ubuntu/monitoring
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      ignore_errors: true
      
    - name: Créer le fichier docker-compose.yml
      copy:
        dest: /home/ubuntu/monitoring/docker-compose.yml
        content: |
          version: '3'
          services:
            prometheus:
              image: prom/prometheus:latest
              volumes:
                - ./prometheus:/etc/prometheus
                - prometheus_data:/prometheus
              command:
                - '--config.file=/etc/prometheus/prometheus.yml'
                - '--storage.tsdb.path=/prometheus'
                - '--web.console.libraries=/usr/share/prometheus/console_libraries'
                - '--web.console.templates=/usr/share/prometheus/consoles'
              ports:
                - 9090:9090
              restart: always
          
            grafana:
              image: grafana/grafana:latest
              volumes:
                - grafana_data:/var/lib/grafana
              environment:
                - GF_SECURITY_ADMIN_PASSWORD=admin
                - GF_USERS_ALLOW_SIGN_UP=false
              ports:
                - 3000:3000
              restart: always
          
          volumes:
            prometheus_data:
            grafana_data:
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      ignore_errors: true
      
    - name: Créer le répertoire pour la configuration de Prometheus
      file:
        path: /home/ubuntu/monitoring/prometheus
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      ignore_errors: true
      
    - name: Créer le fichier de configuration Prometheus
      copy:
        dest: /home/ubuntu/monitoring/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      ignore_errors: true
      
    - name: Démarrer les conteneurs
      shell: |
        cd /home/ubuntu/monitoring
        docker-compose up -d
      become_user: ubuntu
      ignore_errors: true