---
- name: Configuration du GitHub Runner
  hosts: github_runners
  become: true
  roles:
    - role: monolithprojects.github_actions_runner
      vars:
        runner_user: ubuntu
        runner_dir: /home/ubuntu/actions-runner
        access_token: "{{ github_runner_token }}"
        runner_name: "{{ inventory_hostname }}"
        runner_labels:
          - self-hosted
          - linux
          - x64
          - aws
        runner_group: default
