---
- name: Destruction de l'agent Jenkins
  hosts: jenkins_agents
  become: true
  tasks:
    - name: Arrêter le service jenkins-agent
      systemd:
        name: jenkins-agent
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Supprimer le service systemd
      file:
        path: /etc/systemd/system/jenkins-agent.service
        state: absent

    - name: Recharger systemd
      systemd:
        daemon_reload: yes

    - name: Supprimer le répertoire de l'agent
      file:
        path: /home/jenkins
        state: absent

    - name: Supprimer l'utilisateur jenkins
      user:
        name: jenkins
        state: absent
        remove: true
      ignore_errors: true

    - name: Désinstaller Java
      apt:
        name:
          - openjdk-21-jdk
          - openjdk-21-jre
        state: absent
        purge: yes
      ignore_errors: true