---
- name: Destruction du GitHub Runner
  hosts: github_runners
  become: true
  tasks:
    - name: Arrêter le service GitHub Runner
      systemd:
        name: actions.runner.{{ github_account }}-{{ github_repo }}.{{ inventory_hostname }}.service
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Supprimer le runner du repository GitHub
      shell: |
        cd /home/ubuntu/actions-runner
        ./config.sh remove --token {{ github_runner_token }}
      become_user: ubuntu
      ignore_errors: true

    - name: Supprimer le répertoire du runner
      file:
        path: /home/ubuntu/actions-runner
        state: absent

    - name: Supprimer l'utilisateur runner (si créé)
      user:
        name: runner
        state: absent
        remove: true
      ignore_errors: true