---
- name: Configuration du GitHub Runner
  hosts: github_runners
  become: true
  roles:
    - role: monolithprojects.github_actions_runner
      vars:
        runner_user: ubuntu
        runner_dir: /home/ubuntu/actions-runner
        access_token: "{{ github_runner_token }}"
        runner_name: "{{ inventory_hostname }}"
        runner_labels:
          - self-hosted
          - linux
          - x64
          - aws
        runner_group: default

- name: Configuration de Jenkins
  hosts: jenkins
  become: true
  vars:
    jenkins_admin_username: admin
    jenkins_admin_password: "{{ jenkins_admin_password }}"
    jenkins_plugins:
      - git
      - workflow-aggregator
      - pipeline-stage-view
      - docker-workflow
      - kubernetes
      - blueocean
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
  roles:
    - role: geerlingguy.jenkins
