---
- name: Configuration SonarQube
  hosts: sonarqube
  become: true
  vars:
    sonarqube_admin_password: "{{ lookup('env', 'SONARQUBE_ADMIN_PASSWORD') }}"
    sonarqube_admin_username: "{{ lookup('env', 'SONARQUBE_ADMIN_USERNAME') }}"
  
  tasks:
    # Fix Docker APT (cohérent avec les autres)
    - name: Fix Docker APT
      script: ../../scripts/fix_docker_apt.sh

    # Installation base
    - name: Install base packages
      apt:
        name:
          - python3-pip
          - jq
          - curl
          - wget
          - git
        update_cache: yes

    - name: Set timezone
      timezone:
        name: Europe/Paris

    # Docker (même méthode que Jenkins)
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes

    - name: Setup Docker
      block:
        - name: Start Docker
          systemd:
            name: docker
            state: started
            enabled: yes

        - name: Add ubuntu to docker group
          user:
            name: ubuntu
            groups: docker
            append: yes

    # SonarQube via Docker Compose
    - name: Setup SonarQube
      block:
        - name: Copy docker-compose file
          copy:
            src: "../files/sq-docker-compose.yml"
            dest: /home/ubuntu/docker-compose.yml
            owner: ubuntu
            group: ubuntu

        - name: Start SonarQube
          shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
          args:
            chdir: /home/ubuntu
          become_user: ubuntu

        - name: Wait for SonarQube
          uri:
            url: "http://localhost:9000/api/system/status"
          retries: 30
          delay: 10

    - name: Display SonarQube info
      debug:
        msg: 
          - "✅ SonarQube ready at http://{{ inventory_hostname }}:9000"
          - "🔑 Default credentials: admin/admin"
