name: 'Setup AWS Backend'
description: 'Configure le backend AWS S3 et DynamoDB pour Terraform'

inputs:
  bucket_name:
    description: 'Nom du bucket S3'
    required: true
    default: 'projet-c-mohamed'
  table_name:
    description: 'Nom de la table DynamoDB'
    required: true
    default: 'terraform-locks'
  region:
    description: 'Région AWS'
    required: true
    default: 'ca-central-1'

runs:
  using: 'composite'
  steps:
    - name: Create S3 bucket and DynamoDB table
      shell: bash
      run: |
        # Création du bucket S3
        aws s3api create-bucket \
          --bucket ${{ inputs.bucket_name }} \
          --region ${{ inputs.region }} \
          --create-bucket-configuration LocationConstraint=${{ inputs.region }} || true
        
        aws s3api put-bucket-versioning \
          --bucket ${{ inputs.bucket_name }} \
          --versioning-configuration Status=Enabled
        
        echo "✅ Bucket S3 créé/configuré avec succès"

        # Création de la table DynamoDB pour le state lock Terraform
        aws dynamodb create-table \
          --table-name ${{ inputs.table_name }} \
          --attribute-definitions AttributeName=LockID,AttributeType=S \
          --key-schema AttributeName=LockID,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST \
          --region ${{ inputs.region }} || true
        
        echo "✅ Table DynamoDB créée/configurée avec succès"
        echo "🔄 Le backend Terraform est prêt à être utilisé"
