name: Gestion de l'infra App

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action à effectuer'
        required: true
        default: 'app-create'
        type: choice
        options:
          - app-create
          - app-destroy

env:
  TF_BACKEND_BUCKET: projet-c-terraform-state-app

jobs:
  app-create:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'app-create'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-terraform
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS_BASE64 }}
      
      - name: Plan and Apply Terraform
        run: |
          cd $GITHUB_WORKSPACE/../projet-c-app/infra/terraform
          terraform init
          terraform validate
          terraform plan -out="tfplan"
          terraform apply -auto-approve tfplan
          
  app-destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'app-destroy'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-terraform
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS_BASE64 }}
            
      - name: Execute Terraform Destroy
        run: |
          cd $GITHUB_WORKSPACE/../projet-c-app/infra/terraform
          terraform init
          terraform destroy -auto-approve