name: AWS Resources Cleanup

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Tapez "SUPPRIMER" pour confirmer la suppression de toutes les ressources'
        required: true
        type: string
      region:
        description: 'Région AWS à nettoyer'
        required: true
        default: 'ca-central-1'
        type: string

jobs:
  cleanup:
    if: ${{ github.event.inputs.confirm == 'SUPPRIMER' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Decode AWS credentials
        run: |
          echo "${{ secrets.AWS_CREDENTIALS_BASE64 }}" | base64 -d > aws-credentials.json
          echo "AWS_ACCESS_KEY_ID=$(jq -r .aws_access_key_id aws-credentials.json)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(jq -r .aws_secret_access_key aws-credentials.json)" >> $GITHUB_ENV
          rm aws-credentials.json
      
      - name: Configure AWS CLI
        run: |
          aws configure set region ${{ github.event.inputs.region }}
          aws configure set output json
      
      - name: Update cleanup script with selected region
        run: |
          sed -i "s/export AWS_REGION=ca-central-1/export AWS_REGION=${{ github.event.inputs.region }}/" ./infra/scripts/cleanup.sh
      
      - name: Run cleanup script
        run: |
          chmod +x ./infra/scripts/cleanup.sh
          ./infra/scripts/cleanup.sh