name: Coonfiguration avec Ansible

on:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Run Ansible Playbook
        run: |
          cd infra/ansible
          ansible-playbook -i inventory/${{ github.event.inputs.environment }}.yml \
            playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False